apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
labels:
  opendatahub.io/dashboard: "true"
metadata:
  name: ner-custom
  annotations:
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: HuggingFace NER
spec:
  supportedModelFormats:
    - name: pytorch
      version: "1"
      autoSelect: true
  multiModel: false
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Equal"
      value: "true"
      effect: NoSchedule
    - key: "odh-notebook"
      operator: "Equal"
      value: "true"
      effect: NoSchedule
  nodeSelector:
    nvidia.com/gpu.count: "1"
  containers:
    - name: kserve-container
      image: quay.io/jianrzha/ner:0.0.8
      args:
        - --model_name
        - ner
        - --model_checkpoint
        - dslim/bert-base-NER
      env:
        - name: model_checkpoint
          value: dslim/bert-base-NER

